[package]
name = "allium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
embedded-graphics = "0.7.1"
embedded_font = "0.1.3"
evdev = { version = "0.12.1", features = ["tokio"] }
framebuffer = "0.3.1"
rusttype = "0.9.3"
tokio = { version = "1.28.2", features = ["full"] }
