["Amstrad CPC"]
cores = ["crocods"]
patterns = ["CPC"]
extensions = ["sna", "kcr"]

[Arcade]
cores = ["mame2003_plus"]
patterns = ["ARCADE"]
extensions = []

["Atari - 800"]
cores = ["atari800"]
patterns = ["EIGHTHUNDRED"]
extensions = ["xex"]

["Atari 2600"]
cores = ["stella2014"]
patterns = ["ATARI"]
extensions = ["a26"]

["Atari 5200"]
cores = ["a5200"]
patterns = ["FIFTYTWOHUNDRED"]
extensions = ["a52"]

["Atari 7800"]
cores = ["prosystem"]
patterns = ["SEVENTYEIGHTHUNDRED"]
extensions = ["a78"]

["Atari Lynx"]
cores = ["handy"]
patterns = ["LYNX"]
extensions = ["lnx"]

["Sufami Turbo"]
cores = ["snes9x"]
patterns = ["SUFAMI"]
extensions = []

[WonderSwanColor]
cores = ["mednafen_wswan"]
patterns = ["WS"]
extensions = ["ws", "pc2"]

[CPS1]
cores = ["fbalpha2012_cps1"]
patterns = ["CPS1"]
extensions = []

[CPS2]
cores = ["fbalpha2012_cps2"]
patterns = ["CPS2"]
extensions = []

[CPS3]
cores = ["fbalpha2012_cps3"]
patterns = ["CPS3"]
extensions = []

[ColecoVision]
cores = ["bluemsx"]
patterns = ["COLECO"]
extensions = ["ri", "col", "sc"]

[Amiga]
cores = ["puae2021"]
patterns = ["AMIGA"]
extensions = [
    "adf",
    "adz",
    "dms",
    "fdi",
    "ipf",
    "hdf",
    "hdz",
    "lha",
    "slave",
    "info",
    "nrg",
    "mds",
    "uae",
    "rp9",
]

["Commodore 64"]
cores = ["vice_x64"]
patterns = ["COMMODORE"]
extensions = []

[VIC-20]
cores = ["vice_xvic"]
patterns = ["VIC20"]
extensions = [
    "d64",
    "d6z",
    "d71",
    "d7z",
    "d80",
    "d81",
    "d82",
    "d8z",
    "g64",
    "g6z",
    "g41",
    "g4z",
    "x64",
    "x6z",
    "nib",
    "nbz",
    "d2m",
    "d4m",
    "t64",
    "tcrt",
    "prg",
    "p00",
    "crt",
    "cmd",
    "vfl",
    "vsf",
    "gz",
    "20",
    "40",
    "60",
    "a0",
    "b0",
]

["Fairchild ChannelF"]
cores = ["freechaf"]
patterns = ["FAIRCHILD"]
extensions = ["chf"]

[Vectrex]
cores = ["vecx"]
patterns = ["VECTREX"]
extensions = ["vec"]

["Odyssey 2"]
cores = ["o2em"]
patterns = ["ODYSSEY"]
extensions = []

[Intellivision]
cores = ["freeintv"]
patterns = ["INTELLIVISION"]
extensions = ["int"]

["Mega Duck"]
cores = ["sameduck"]
patterns = ["MEGADUCK"]
extensions = []

[MS-DOS]
cores = ["dosbox_pure"]
patterns = ["DOS"]
extensions = [
    "dosz",
    "exe",
    "com",
    "bat",
    "ins",
    "ima",
    "vhd",
    "jrc",
    "tc",
    "m3u8",
    "conf",
]

[MSX]
cores = ["bluemsx"]
patterns = ["MSX"]
extensions = []

[SuperGrafx]
cores = ["mednafen_supergrafx"]
patterns = ["SGFX"]
extensions = ["sgx"]

["TurboGrafx CD"]
cores = ["mednafen_pce_fast"]
patterns = ["PCECD"]
extensions = []

[TurboGrafx-16]
cores = ["mednafen_pce_fast"]
patterns = ["PCE"]
extensions = ["pce"]

["Famicom Disk Syst."]
cores = ["fceumm"]
patterns = ["FDS"]
extensions = ["fds"]

["Game & Watch"]
cores = ["gw"]
patterns = ["GW"]
extensions = ["mgw"]

["Game Boy"]
cores = ["gambatte", "tgbdual"]
patterns = ["GB", "TGB_Dual"]
extensions = ["gb"]

["Game Boy Color"]
cores = ["gambatte", "mgba"]
patterns = ["GBC", "SGB"]
extensions = ["gbc"]

["Game Boy Advance"]
cores = ["gpsp", "mgba"]
patterns = ["GBA"]
extensions = ["gba"]

[NES]
cores = ["fceumm", "nestopia"]
patterns = ["FC", "NES"]
extensions = ["nes", "unif", "unf"]

["Pokémon Mini"]
cores = ["pokemini"]
patterns = ["POKE", "PKM"]
extensions = ["min"]

[Satellaview]
cores = ["snes9x"]
patterns = ["SATELLAVIEW"]
extensions = ["st"]

[SNES]
cores = ["mednafen_supafaust", "snes9x"]
patterns = ["SFC", "SNES"]
extensions = ["sfc", "smc", "swc", "fig"]

["Virtual Boy"]
cores = ["mednafen_vb"]
patterns = ["VB"]
extensions = ["vb", "vboy"]

["Phillips Videopac+"]
cores = ["o2em"]
patterns = ["VIDEOPAC"]
extensions = []

[PICO-8]
cores = ["fake08"]
patterns = ["PICO"]
extensions = ["p8", "png"]

["Ports Collection"]
path = "/mnt/SDCARD/.allium/cores/pak/launch.sh"
patterns = ["PORTS", "SH", "NATIVE"]
extensions = ["port"]

[ScummVM]
cores = ["scummvm"]
patterns = ["SCUMMVM"]
extensions = ["scummvm", "target"]

["Genesis 32X"]
cores = ["picodrive"]
patterns = ["THIRTYTWOX"]
extensions = ["32x"]

["Sega CD"]
cores = ["picodrive"]
patterns = ["SEGACD"]
extensions = []

["Game Gear"]
cores = ["picodrive"]
patterns = ["GG"]
extensions = ["gg"]

[Genesis]
cores = ["picodrive"]
patterns = ["MD"]
extensions = ["gen", "smd", "md"]

["Master System"]
cores = ["picodrive"]
patterns = ["MS"]
extensions = ["sms"]

[SG-1000]
cores = ["gearsystem"]
patterns = ["SEGASGONE"]
extensions = ["sg"]

["ZX Spectrum"]
cores = ["fuse"]
patterns = ["ZXS"]
extensions = ["tzx", "z80", "rzx", "scl", "trd"]

["Neo Geo"]
cores = ["fbalpha2012_neogeo"]
patterns = ["NEOGEO"]
extensions = []

["Neo Geo CD"]
cores = ["neocd"]
patterns = ["NEOCD"]
extensions = []

["Neo Geo Pocket Color"]
cores = ["mednafen_ngp"]
patterns = ["NGP", "NGC"]
extensions = ["ngp", "ngc"]

[PlayStation]
cores = ["pcsx_rearmed"]
patterns = ["PSX", "PS", "PS1"]
extensions = ["mdf", "pbp", "toc", "cbn"]

[TIC-80]
cores = ["tic80"]
patterns = ["TIC"]
extensions = ["tic", "fd", "sap", "k7", "m7"]

["Watara Supervision"]
cores = ["potator"]
patterns = ["SUPERVISION"]
extensions = ["sv"]

[J2ME]
cores = ["squirreljme"]
patterns = ["J2ME"]
extensions = []

[PC-98]
cores = ["np2kai"]
patterns = ["PC98", "PCNINETYEIGHT", "NINETYEIGHT"]
extensions = []

[PC-FX]
cores = ["mednafen_pcfx"]
patterns = ["PCFX"]
extensions = []

[NXEngine]
cores = ["nxengine"]
patterns = ["NXENGINE"]
file_name = ["Doukutsu.exe"]

["SH Launcher"]
cores = ["sh_launcher"]
extensions = ["sh"]
