["Amstrad CPC"]
cores = ["crocods"]
patterns = ["CPC"]
extensions = ["sna", "kcr"]

[Arcade]
cores = ["mame2003_plus", "fbneo", "fbalpha2012", "fbalpha2012_cps1", "fbalpha2012_cps2", "fbalpha2012_cps3", "km_mame2003_xtreme", "mame2003_midway", "mame2003", "mame2000", "mba_mini"]
patterns = ["ARCADE"]

["Atari - 800"]
cores = ["atari800"]
patterns = ["EIGHTHUNDRED"]
extensions = ["xex"]

["Atari 2600"]
cores = ["stella2014"]
patterns = ["ATARI"]
extensions = ["a26"]

["Atari 5200"]
cores = ["a5200"]
patterns = ["FIFTYTWOHUNDRED"]
extensions = ["a52"]

["Atari 7800"]
cores = ["prosystem"]
patterns = ["SEVENTYEIGHTHUNDRED"]
extensions = ["a78"]

["Atari Jaguar"]
cores = ["virtualjaguar"]
patterns = ["JAGUAR"]
extensions = ["j64", "jag"]

["Atari Lynx"]
cores = ["handy", "mednafen_lynx"]
patterns = ["LYNX"]
extensions = ["lnx"]

["Atari ST"]
cores = ["hatari"]
patterns = ["ATARIST"]

["Sufami Turbo"]
cores = ["snes9x"]
patterns = ["SUFAMI"]

[WonderSwanColor]
cores = ["mednafen_wswan"]
patterns = ["WS"]
extensions = ["ws", "pc2"]

[CPS1]
cores = ["fbalpha2012_cps1", "mame2003_plus", "fbneo", "fbalpha2012", "fbalpha2012_cps1", "km_mame2003_xtreme", "mame2003_midway", "mame2003", "mame2000", "mba_mini"]
patterns = ["CPS1"]

[CPS2]
cores = ["fbalpha2012_cps2", "mame2003_plus", "fbneo", "fbalpha2012", "fbalpha2012_cps2", "km_mame2003_xtreme", "mame2003_midway", "mame2003", "mame2000", "mba_mini"]
patterns = ["CPS2"]

[CPS3]
cores = ["fbalpha2012_cps3", "mame2003_plus", "fbneo", "fbalpha2012", "fbalpha2012_cps3", "km_mame2003_xtreme", "mame2003_midway", "mame2003", "mame2000", "mba_mini"]
patterns = ["CPS3"]

[ColecoVision]
cores = ["bluemsx"]
patterns = ["COLECO"]
extensions = ["ri", "col", "sc"]

[Amiga]
cores = ["puae2021", "puae", "uae4arm"]
patterns = ["AMIGA"]
extensions = [
    "adf",
    "adz",
    "dms",
    "fdi",
    "ipf",
    "hdf",
    "hdz",
    "lha",
    "slave",
    "info",
    "nrg",
    "mds",
    "uae",
    "rp9",
]

["Commodore 64"]
cores = ["vice_x64"]
patterns = ["COMMODORE"]

[VIC-20]
cores = ["vice_xvic"]
patterns = ["VIC20"]
extensions = [
    "d64",
    "d6z",
    "d71",
    "d7z",
    "d80",
    "d81",
    "d82",
    "d8z",
    "g64",
    "g6z",
    "g41",
    "g4z",
    "x64",
    "x6z",
    "nib",
    "nbz",
    "d2m",
    "d4m",
    "t64",
    "tcrt",
    "prg",
    "p00",
    "crt",
    "cmd",
    "vfl",
    "vsf",
    "gz",
    "20",
    "40",
    "60",
    "a0",
    "b0",
]

["Fairchild ChannelF"]
cores = ["freechaf"]
patterns = ["FAIRCHILD"]
extensions = ["chf"]

[Vectrex]
cores = ["vecx"]
patterns = ["VECTREX"]
extensions = ["vec"]

["Odyssey 2"]
cores = ["o2em"]
patterns = ["ODYSSEY"]

[Intellivision]
cores = ["freeintv"]
patterns = ["INTELLIVISION"]
extensions = ["int"]

["Mega Duck"]
cores = ["sameduck"]
patterns = ["MEGADUCK"]

[MS-DOS]
cores = ["dosbox_pure", "dosbox_pure_0.9.7"]
patterns = ["DOS"]
extensions = [
    "dosz",
    "exe",
    "com",
    "bat",
    "ins",
    "ima",
    "vhd",
    "jrc",
    "tc",
    "m3u8",
    "conf",
]

[MSX]
cores = ["bluemsx", "fmsx"]
patterns = ["MSX"]
extensions = ["mx1", "mx2" ]

[SuperGrafx]
cores = ["mednafen_supergrafx"]
patterns = ["SGFX"]
extensions = ["sgx"]

["TurboGrafx CD"]
cores = ["mednafen_pce_fast"]
patterns = ["PCECD"]

[TurboGrafx-16]
cores = ["mednafen_pce_fast"]
patterns = ["PCE"]
extensions = ["pce"]

["Famicom Disk Syst."]
cores = ["fceumm"]
patterns = ["FDS"]
extensions = ["fds"]

["Game & Watch"]
cores = ["gw"]
patterns = ["GW"]
extensions = ["mgw"]

["Game Boy"]
cores = ["gambatte", "tgbdual", "gearboy", "mgba", "vbam", "vba_next"]
patterns = ["GB", "TGB_Dual"]
extensions = ["gb"]

["Game Boy Color"]
cores = ["gambatte", "tgbdual", "gearboy", "mgba", "vbam", "vba_next"]
patterns = ["GBC", "SGB"]
extensions = ["gbc"]

["Game Boy Advance"]
cores = ["gpsp", "mgba", "vbam", "vba_next"]
patterns = ["GBA"]
extensions = ["gba"]

["Super Game Boy"]
cores = ["mgba", "tgbdual", "gearboy", "bsnes"]
patterns = ["SGB"]

[NES]
cores = ["fceumm", "nestopia"]
patterns = ["FC", "NES"]
extensions = ["nes", "unif", "unf"]

["Pokémon Mini"]
cores = ["pokemini"]
patterns = ["POKE", "PKM"]
extensions = ["min"]

[Satellaview]
cores = ["snes9x"]
patterns = ["SATELLAVIEW"]
extensions = ["st"]

[SNES]
cores = ["mednafen_supafaust", "snes9x", "snes9x2010", "snes9x2005", "snes9x2005_plus", "snes9x2002", "chimerasnes"]
patterns = ["SFC", "SNES"]
extensions = ["sfc", "smc", "swc", "fig"]

["Virtual Boy"]
cores = ["mednafen_vb"]
patterns = ["VB"]
extensions = ["vb", "vboy"]

["Phillips Videopac+"]
cores = ["o2em"]
patterns = ["VIDEOPAC"]

[PICO-8]
cores = ["fake08", "retro8"]
patterns = ["PICO"]
extensions = ["p8", "png"]

["Ports Collection"]
path = "/mnt/SDCARD/.allium/cores/pak/launch.sh"
patterns = ["PORTS", "SH", "NATIVE"]
extensions = ["port"]

[ScummVM]
cores = ["scummvm"]
patterns = ["SCUMMVM"]
extensions = ["scummvm", "target"]

["Genesis 32X"]
cores = ["picodrive"]
patterns = ["THIRTYTWOX"]
extensions = ["32x"]

["Sega CD"]
cores = ["picodrive", "genesis_plus_gx"]
patterns = ["SEGACD"]

["Game Gear"]
cores = ["picodrive", "genesis_plus_gx"]
patterns = ["GG"]
extensions = ["gg"]

[Genesis]
cores = ["picodrive", "genesis_plus_gx"]
patterns = ["MD"]
extensions = ["gen", "smd", "md"]

["Master System"]
cores = ["picodrive", "genesis_plus_gx"]
patterns = ["MS"]
extensions = ["sms"]

[SG-1000]
cores = ["gearsystem"]
patterns = ["SEGASGONE"]
extensions = ["sg"]

["Sega VMU"]
cores = ["vemulator"]
patterns = ["VMU"]

["ZX Spectrum"]
cores = ["fuse"]
patterns = ["ZXS"]
extensions = ["tzx", "z80", "rzx", "scl", "trd"]

["Neo Geo"]
cores = ["fbalpha2012_neogeo"]
patterns = ["NEOGEO"]

["Neo Geo CD"]
cores = ["neocd"]
patterns = ["NEOCD"]

["Neo Geo Pocket Color"]
cores = ["mednafen_ngp"]
patterns = ["NGP", "NGC"]
extensions = ["ngp", "ngc"]

[PlayStation]
cores = ["pcsx_rearmed"]
patterns = ["PSX", "PS", "PS1"]
extensions = ["mdf", "pbp", "toc", "cbn"]

[TIC-80]
cores = ["tic80"]
patterns = ["TIC"]
extensions = ["tic", "fd", "sap", "k7", "m7"]

["Watara Supervision"]
cores = ["potator"]
patterns = ["SUPERVISION"]
extensions = ["sv"]

[PC-8000]
cores = ["quasi88"]
patterns = ["PC8000"]

[PC-98]
cores = ["np2kai", "nekop2"]
patterns = ["PC98", "PCNINETYEIGHT", "NINETYEIGHT"]

[PC-FX]
cores = ["mednafen_pcfx"]
patterns = ["PCFX"]

["Cave Story"]
cores = ["nxengine"]
patterns = ["NXENGINE"]
file_name = ["Doukutsu.exe"]

["SH Launcher"]
cores = ["sh_launcher"]
extensions = ["sh"]

["Sinclair ZX81"]
cores = ["zx81"]
patterns = ["ZX81", "ZXEIGHTYONE"]

[ChaiLove]
cores = ["chailove"]
patterns = ["CHAILOVE"]

[Daphne]
cores = ["daphne"]
patterns = ["DAPHNE"]
extensions = ["daphne"]

[EasyRPG]
cores = ["easyrpg"]
patterns = ["EASYRPG"]

["Wolfenstein 3D"]
cores = ["ecwolf"]
patterns = ["ECWOLF"]

["Game Music Emu"]
cores = ["gme"]
patterns = ["GME"]

["LÖVE"]
cores = ["lutro"]
patterns = ["LOVE"]
extensions = ["love"]

["Palm OS"]
cores = ["mu"]
patterns = ["PALMOS"]
extensions = ["prc", "pqa"]

["Texas Instruments TI-83"]
cores = ["numero"]
patterns = ["TI83"]

[3DO]
cores = ["opera"]
patterns = ["PANASONIC", "3DO"]

[Doom]
cores = ["prboom"]
patterns = ["DOOM", "PRBOOM"]
extensions = ["wad", "iwad", "pwad"]

["Sharp X1"]
cores = ["x1"]
patterns = ["SHARPX1"]

["Sharp X68000"]
cores = ["px68k"]
patterns = ["X68000"]

[Flashback]
cores = ["reminiscence"]
patterns = ["FLASHBACK"]

["Thomson"]
cores = ["theodore"]
patterns = ["THOMSON"]

[Quake]
cores = ["tyrquake"]
patterns = ["QUAKE"]

[MicroW8]
cores = ["uw8"]
patterns = ["MICROW8"]

[Uzebox]
cores = ["uzem"]
patterns = ["UZEBOX"]

["GCE Vectrex"]
cores = ["vecx"]
patterns = ["VECRTEX"]

["Rick Dangerous"]
cores = ["xrick"]
patterns = ["XRICK"]