[cores."dosbox_pure_0.9.7"]
name = "DOSBox Pure 0.9.7"

[cores.a5200]
name = "A5200"

[cores.atari800]
name = "Atari 800"

[cores.bluemsx]
name = "blueMSX"

[cores.bsnes]
name = "bsnes"

[cores.chailove]
name = "ChaiLove"

[cores.chimerasnes]
name = "ChimeraSNES"

[cores.crocods]
name = "CrocoDS"

[cores.daphne]
name = "Daphne"

[cores.dosbox_pure]
name = "DOSBox Pure"

[cores.easyrpg]
name = "EasyRPG"

[cores.ecwolf]
name = "ECWolf"

[cores.fake08]
name = "FAKE-08"

[cores.fbalpha2012]
name = "FinalBurn Alpha 2012"
swap = true

[cores.fbalpha2012_cps1]
name = "FBA 2012 CPS1"
swap = true

[cores.fbalpha2012_cps2]
name = "FBA 2012 CPS2"
swap = true

[cores.fbalpha2012_cps3]
name = "FBA 2012 CPS3"
swap = true

[cores.fbalpha2012_neogeo]
name = "FBA 2012 NeoGeo"
swap = true

[cores.fbneo]
name = "FinalBurn Neo"
swap = true

[cores.fceumm]
name = "FCEUmm"

[cores.fmsx]
name = "fMSX"

[cores.freechaf]
name = "FreeChaF"

[cores.freeintv]
name = "FreeIntv"

[cores.fuse]
name = "Fuse"

[cores.gambatte]
name = "Gambatte"

[cores.gearboy]
name = "Gearboy"

[cores.gearsystem]
name = "Gearsystem"

[cores.genesis_plus_gx]
name = "Genesis Plus GX"

[cores.gme]
name = "Game Music Emu"

[cores.gpsp]
name = "gpSP"

[cores.gw]
name = "Game & Watch"

[cores.handy]
name = "Handy"

[cores.hatari]
name = "Hatari"

[cores.km_mame2003_xtreme]
name = "MAME 2003 Xtreme"

[cores.lutro]
name = "Lutro"

[cores.mame2000]
name = "MAME 2000"

[cores.mame2003]
name = "MAME 2003"

[cores.mame2003_midway]
name = "MAME 2003 Midway"

[cores.mame2003_plus]
name = "MAME 2003-Plus"

[cores.mba_mini]
name = "M.B.A mini"

[cores.mednafen_lynx]
name = "Beetle Lynx"

[cores.mednafen_ngp]
name = "Beetle NeoGeo Pocket"

[cores.mednafen_pce_fast]
name = "Beetle PCE FAST"

[cores.mednafen_pcfx]
name = "Beetle PC-FX"

[cores.mednafen_supafaust]
name = "Beetle Supafaust"

[cores.mednafen_supergrafx]
name = "Beetle SuperGrafx"

[cores.mednafen_vb]
name = "Beetle VB"

[cores.mednafen_wswan]
name = "Beetle Cygne"

[cores.mgba]
name = "mGBA"
swap = true

[cores.mu]
name = "mu"

[cores.nekop2]
name = "Neko Project II"

[cores.neocd]
name = "NeoCD"

[cores.nestopia]
name = "Nestopia"

[cores.np2kai]
name = "Neko Project II Kai"

[cores.numero]
name = "Numero"

[cores.nxengine]
name = "NXEngine"

[cores.o2em]
name = "O2EM"

[cores.opera]
name = "Opera"

[cores.pcsx_rearmed]
name = "PCSX ReARMed"

[cores.picodrive]
name = "PicoDrive"

[cores.pokemini]
name = "PokeMini"

[cores.potator]
name = "Potator"

[cores.prboom]
name = "PRBoom"

[cores.prosystem]
name = "ProSystem"

[cores.puae]
name = "PUAE"

[cores.puae2021]
name = "PUAE 2021"

[cores.px68k]
name = "PX68k"

[cores.quasi88]
name = "QUASI88"

[cores.reminiscence]
name = "REminiscence"

[cores.retro8]
name = "Retro8"

[cores.sameduck]
name = "SameDuck"

[cores.scummvm]
name = "ScummVM"

[cores.sh_launcher]
name = "SH Launcher"

[cores.snes9x]
name = "Snes9x"

[cores.snes9x2002]
name = "Snes9x 2002"

[cores.snes9x2005]
name = "Snes9x 2005"

[cores.snes9x2005_plus]
name = "Snes9x 2005 Plus"

[cores.snes9x2010]
name = "Snes9x 2010"

[cores.stella2014]
name = "Stella 2014"

[cores.tgbdual]
name = "TGB Dual"

[cores.theodore]
name = "Theodore"

[cores.tic80]
name = "TIC-80"

[cores.tyrquake]
name = "TyrQuake"

[cores.uae4arm]
name = "UAE4ARM"

[cores.uw8]
name = "uw8"

[cores.uzem]
name = "Uzem"

[cores.vba_next]
name = "VBA Next"

[cores.vbam]
name = "VBA-M"

[cores.vecx]
name = "VecX"

[cores.vemulator]
name = "VEmulator"

[cores.vice_x64]
name = "VICE x64"

[cores.vice_xvic]
name = "VICE xvic"

[cores.virtualjaguar]
name = "Virtual Jaguar"

[cores.x1]
name = "X1"

[cores.xrick]
name = "XRick"

[cores.zx81]
name = "ZX81"

